name: CD Workflow

on:
  push:
    branches:
      - master
jobs:
  my-job-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy
