name: CD Workflow

on:
  push:
    branches:
      - master
jobs:
  my-job-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v3

      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa

      - name: Git config
        run: |
          git config --global user.email "lauxdl@gmail.com"
          git config --global user.name "lauxdl"


      - name: Install all dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy -- -r git@github.com:lauxdl/lemon-module07-manual-gh-pages-deploy.git
